``enabled``
***********

**type**: ``bool`` **default**: ``false``

If ``true``, the admin classes and extensions of this package are loaded and
available for Sonata Admin.

.. tip::

    If you do not see this admin on the Sonata dashboard, you need to configure
    the dashboard to show the admin service in question. Read more about this
    in `the Sonata Admin documentation`_.

.. _the Sonata Admin documentation: https://sonata-project.org/bundles/admin/3-x/doc/reference/dashboard.html
