.. note::

    To focus our efforts onto a manageable number of packages, this package is
    currently *not* maintained. Security fixes and submitted bug fixes will
    still be released, but no new features should be expected. This bundle
    might have outdated documentation, there is no support from the CMF team
    and you should not expect bugs to be fixed.

    If you want to help co-maintaining this package, tell us in a GitHub issue
    or in #symfony_cmf of the `Symfony devs slack`_.

.. _`Symfony devs slack`: https://slackinvite.me/to/symfony-devs
