.. caution::

    The cookbook is in the process of being restructured. Some documentation is
    outdated, notable configuration examples. If something does not work, please
    have a look in the Reference section and send pull requests to fix things,
    or just open an issue on github so that we know about the problem.

    Refer to `the documentation issues`_ to help us bringing this article up to
    date.

.. _`the documentation issues`: https://github.com/symfony-cmf/symfony-cmf-docs/issues/
