* **Database**

   * :doc:`database/choosing_storage_layer`

* **Editions**

   * :doc:`editions/cmf_sandbox`
   * :doc:`editions/cmf_core`
* :doc:`installing_configuring_doctrine_phpcr_odm`
* :doc:`installing_configuring_inline_editing`
* :doc:`creating_cms_using_cmf_and_sonata`
* :doc:`using_blockbundle_and_contentbundle`
* :doc:`handling_multilang_documents`
* :doc:`using_a_custom_route_repository`
