* **Database**

  * :doc:`database/choosing_storage_layer`
  * :doc:`database/choosing_phpcr_implementation`
  * :doc:`database/running_jackrabbit`
  * :doc:`database/doctrine_cache`

* **Editions**

  * :doc:`Installing the CMF Standard Edition <../book/installation>` (in the book)
  * :doc:`editions/cmf_sandbox`
  * :doc:`editions/cmf_core`

* :doc:`creating_a_cms/index`
* :doc:`exposing_content_via_rest`
